/**
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <https://unlicense.org>
 */
package de.protubero.ajs;

import java.io.IOException;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;

import org.apache.commons.io.IOUtils;
import org.jooby.Env;
import org.jooby.Jooby;
import org.jooby.MediaType;
import org.jooby.Request;
import org.jooby.Response;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.inject.Binder;
import com.typesafe.config.Config;
import com.typesafe.config.ConfigFactory;

import javaslang.Function2;
import javaslang.control.Option;
import javaslang.control.Try;

/**
 * A jooby module to serve the js/html/css files generated by Angular.
 * These files are packed in a JAR file which is part of the classpath (In the distribution, not in the dev setup!).
 * 
 * 
 * 
 * @author MSchaefer
 *
 */
public class AngularClient implements Jooby.Module {

	final static Logger logger = LoggerFactory.getLogger(AngularClient.class);

	public static final String INDEX_FILENAME = "index.html";

	public static final String ERROR_PAGE_TEMPLATE = "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>#title</title></head><body>#content</body></html>";

	public static final Function2<String, String, String> errorPageCreator = (title, content) -> {
		return ERROR_PAGE_TEMPLATE.replaceFirst("#title", title).replace("#content", content);
	};

	private Map<String, Option<byte[]>> fileNameToContentMap = new HashMap<>();

	private byte[] loadFileByName(String fileName) {
		Option<byte[]> content = fileNameToContentMap.get(fileName);
		if (content == null) {
			content = Option.none();
			try (InputStream is = getClass().getResourceAsStream("/client/" + fileName)) {
				content = Option.of(IOUtils.toByteArray(is));
			} catch (IOException e) {
				logger.debug("error loading file " + fileName, e);
			}
			fileNameToContentMap.put(fileName, content);
		} 
		
		if (content.isDefined()) {
			return content.get();
		} else {
			throw new RuntimeException("Invalid file name: " + fileName);
		}
	}

	@Override
	public void configure(Env env, Config conf, Binder binder) throws Throwable {
		env.router().get("/*", (req, rsp) -> request(req, rsp, req.path().substring(1)));
	}

	public void request(final Request req, final Response rsp, String fileName) {
		if (fileName.length() == 0) {
			fileName = INDEX_FILENAME;
		}
		
		logger.debug("request client file '" + fileName + "'");

		final String fileToLoad = fileName; 
		
		Try<byte[]> tTry = Try.of(() -> loadFileByName(fileToLoad));
		
		tTry = tTry.recoverWith(e -> {
			if (fileToLoad.equals(INDEX_FILENAME)) {
				return Try.of(() -> errorPageCreator.apply("Client", "Angular Client not available").getBytes());
			} else {
				return Try.failure(e);
			}
		});
		
		tTry.onFailure(exc -> {
			rsp.status(404);
		});

		tTry.onSuccess(bytes -> {
			Try.run(() -> { 
				rsp.status(200)
				.type(MediaType.byPath(fileToLoad).orElseThrow(() -> new RuntimeException("unable to determine media type of file " + fileToLoad)))
				.send(bytes);
			}).onFailure(e -> {
				logger.debug("error sending response", e);
			});
		});
	}
	
	public Config config() {
		return ConfigFactory.parseResources(getClass(), "angular.properties");
	}
}
